### PR TITLE
Closes i-RIC/iriclib#18

### PR DESCRIPTION
**Pull request by kskinoue0612**
This closes issue #18.

Please note that this is the "first step". I mean, when this issue is fixed, we have to use `FileLocker` to lock Case1.cgn.lock not only in solvers, but also in iRIC GUI too, to make the "locking" framework works correctly.

I'll engage that issue in iRIC GUI, when this pull request is merged.

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

Please see my pull request on [kskinoue0612/iriclib](https://github.com/kskinoue0612/iriclib/pull/1)

Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

I've merged your pr.
I think it is OK now, so please merge pull request.

Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

Please do not merge this pull request, because I've noticed that maybe the implementation
is not complete yet.

Thanks,
Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

I've figured out the issue, and added two unit case programs:

* unittest_cg_open_modify
* unittest_cg_open_read

To make the unit tests pass, FileLocker implementation is updated.
README.md in unittest_cg_open_modify folder describes how to do the unit tests.

Please check them, and the unit test passes on your environment, please merge the pull requests.

When you have questions or comments, please let me know.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I wasn't able to get the 2e41ae1 version to fail.  I think what may have happened with your testing (because it happened to me today) was that maybe unittest_cg_open_modify/unittest_cg_open_read was loading an older iriclib.dll.

I've made a pr (kskinoue0612/iriclib#2) that fixes a few things for the cmake version.

Thanks,
Scott

**Pull request merged**
