### PR TITLE
Closes #80

### LINKED ISSUE #80: Make it possible to output calculation result when there is no grid
iRIClib expects that there is a grid when calculation result is output. If not, error occurs.

To generalize the library, make it possible to output calculation result when there is no grid.

### PR DESCRIPTION
**Pull request by kskinoue0612**
You can test this by checking that the unit test runs successfully.

Please not that this pull request is dependent on #84. Please merge this after merging #84.

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

I think you forgot to add a file.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for your notification.
I've fixed CMakeLists.txt, and fixed unit test code.

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Sorry, I didn't notice and added files.  Otherwise, I would have been able to fix myself.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

It’s OK, thanks for reviewing and merging the pull request.

Keisuke

**Pull request merged**
