### PR TITLE
Closes i-RIC/iriclib#15

### PR DESCRIPTION
**Pull request by scharlton2**
Hi Keisuke,

I didn't implement ` cg_iRIC_Read_Sol_Cell_Count_Mul ` since it seemed to only duplicate what `cg_iRIC_Read_Sol_Count_Mul` did.  I'll work on the documentation when everything is finalized.

Thanks,
Scott

### CODE REVIEW

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for implementing the functions.
This is something rather big, so give me some time for reviewing this.

Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

I've reviewed the commits.
Now iriclib has test cases using not only ADF version CGNS files, but also HDF5 version CGNS files. Thanks, it is a good improvements.

I've made some changes, and commited to my repository:

https://github.com/kskinoue0612/iriclib/tree/issue-15

The changes I've made is:

* Made the log "straight". I mean, rebase to master, and removed commit to merge master.
* Added two function to FORTRAN interface, using `make_iric_ftoc.php`.

Please check the modification, and if think OK, let me know.

Thanks,
Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

If you think my rebased version branch is acceptable, please do the following operation.
In the following code, I guess your repository is named "scott", and my repository is named "inoue" in your local environment.

```
git fetch inoue
git checkout issue-15
git reset --hard inoue/issue-15
git push scott issue-15 -f
```

I welcome your comments or modifications, if you have ideas about improvements,

Thanks,
Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Everything looks good.  I've done what you've asked so you can close the pull request if you want.

Thanks,
Scott

**Pull request merged**
