### PR TITLE
Close #86

### LINKED ISSUE #86: Add python interface
Add python interface to iriclib functions, so that we can develop solvers in python.

### PR DESCRIPTION
**Pull request by kskinoue0612**
To test this, please do the followings:

1. Install Miniconda. It is available from the following URL. For example, install to D:\miniconda3.
https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
2. Install swig, and add the folder where swig.exe is installed, to PATH environmental variable. It is available from the following URL:
http://www.swig.org/
3. Build iriclib.dll, as usual.
4. "Open Anaconda Prompt (miniconda3)", and enter the following command, to create virtual env named "iric".
```
conda create -n "iric" python=3
```
3. Modify python_binding/build.bat, so that it can include Python.h, cgnslib.h, and build and link against python.
4. Copy the following files to D:\miniconda3\envs\iric\Lib\site-packages (or where you've installed miniconda):

    * iriclib.dll
    * cgnslib.dll
    * hdf5.dll
    * szip.dll
    * zlib.dll

5. In "Anaconda Prompt (miniconda3)", input the following commands, to make sure that iric module is installed properly.
```
conda activate iric
python
import iric
```

6. Please run unit tests with the following command:
```
cd (Where iriclib exists)\python_binding\unittests_cgnsfile
python run.py

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

Sorry, I keep forgetting to check iriclib for PRs.

I got two failures when running run.py:

`cg_iRIC_Read_BC_IndicesSize2_Mul() size == 5 [NG]`
and
`cg_iRIC_Read_BC_IndicesSize2() size == 5 [NG]`

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for reviewing the pull request.

I’m going check the issue you reported, in a few days.

Thank you,

Keisuke

2020年12月13日(日) 9:53 Scott Charlton <notifications@github.com>:

**Comment by kskinoue0612** [comment]
Hi Scott,

Sorry that it took time to fix. I was busy on other projects.
I think I've fixed the issue.
* Fixed cg_iRIC_Write_BC_indices() used from Python, because it had bug.
* Fixed unit testing code.

I've run run.py, and made sure that no "[NG]" is included in the log now.

Thank you,
Keisuke

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for reviewing.
I hope you'll have a happy new year!

Keisuke

**Comment by scharlton2** [comment]
Thanks Keisuke,

Hope you do too.

Scott

**Pull request merged**
